### ISSUE TITLE
Support Darwin arm64 builds

### ISSUE THREAD

**Issue by pmalek** [quarkslab/kdigger#13]
Given that kdigger is written in Go it should be fairly straightforward to provide those builds.

**Comment by mtardy** [comment]
Sorry for the late reply but yes it should be _fairly straightforward_, feel free to update the Makefile `release` target in a PR to add `darwin_arm64` and change `darwin` into `darwin_amd64`. It will be my pleasure to merge this and then do the release on the GitHub repo.
