### ISSUE TITLE
[feat] Add flag for namespaces during kdigger gen 

### ISSUE THREAD

**Issue by kranurag7** [quarkslab/kdigger#8]
While `kdigger gen` the namespace flag is missing. It will be good to have the namespace flag during  kdigger gen. 
One can still use `./kdigger gen | kubectl -n <namespace> apply -f -` but adding a flag will help in generation of manifest along with namespace and then editing the same manifest after that. 

/assign

**Comment by mtardy** [comment]
Hey, thanks for opening that issue and actually taking the time to implement it! I will take a look at your PR right now!
